backend:
  image: "shreybatra/sample-backend"
  replicas: 1
  env:
    REDIS_URI: "redis://redis-svc:6379"

frontend:
  image: "shreybatra/sample-frontend"
  replicas: 1
  env:
    BACKEND_URL: "http://backend-svc:8000"

redis:
  image: "redis"
  replicas: 1

service:
  backend:
    name: backend-svc
    type: ClusterIP
    port: 8000
    targetPort: 8000
  frontend:
    name: frontend-svc
    type: NodePort
    port: 5173
    targetPort: 5173
    nodePort: 31000
  redis:
    name: redis-svc
    type: ClusterIP
    port: 6379
    targetPort: 6379

