apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.backend.name }}
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.backend.port }}
      targetPort: {{ .Values.service.backend.targetPort }}
  type: {{ .Values.service.backend.type }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.frontend.name }}
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.service.frontend.port }}
      targetPort: {{ .Values.service.frontend.targetPort }}
      nodePort: {{ .Values.service.frontend.nodePort }}
  type: {{ .Values.service.frontend.type }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.redis.name }}
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: {{ .Values.service.redis.port }}
      targetPort: {{ .Values.service.redis.targetPort}}
  type: {{ .Values.service.redis.type }}
